name: godPowers
main: com.FriedTaco.taco.godPowers.godPowers
version: ${project.version}
description: ${git.commit.id.abbrev}
author: Swift
commands:
    bless:
        description: Enchants all items in your inventory!
        usage: /bless
    demigod:
        description: Reduces all damage you take!
        usage: /demigod
    die:
        description: Kills yourself!
        usage: /die
    dupe:
        description: Dupes the item you're holding!
        usage: /dupe <amount>
    fusrodah:
        description: Puts knockback level 10 on the item in your hand!
        usage: /fusrodah
    gaia:
        description: Beautify the earth with every step you take!
        usage: /gaia
    godmode:
        description: Makes you immune to all damage!
        usage: /godMode
    godmodeon:
        description: Enable godmode (Temporary fix for conflict with Essentials).
        usage: /godmodeon
    godmodeoff:
        description: Disable godmode (Temporary fix for conflict with Essentials).
        usage: /godmodeoff
    godpowers:
        description: Displays commands and credits information
        usage: /godpowers
    hades:
        description: Corrupts the world beneath your feet!
        usage: /hades
    heal:
        description: Heals you or the player you specify!
        usage: /heal
    hermes:
        description: Makes you run as fast as hermes!
        usage: /hermes
    inferno:
        description: Burn the ground beneath you in your fiery rage!
        usage: /inferno
    itemrepair:
        description: See repair
        usage: /itemrepair
    jesus:
        description: Grants you the ability to walk on water and lava!
        usage: /jesus
    maim:
        description: Nearly beat a specified player to death!
        usage: /maim
    medusa:
        description: Curses you with the ability to turn people to stone!
        usage: /medusa
    midas:
        description: Upgrades and enchants your tools to gold!
        usage: /midas
    myballsareonfire:
        description: See vulcan.
        usage: /myballsareonfire
    plutus:
        description: Puts fortune level 10 on the item in your hand!
        usage: /plutus
    poseidon:
        description: Grants you poseidon's powers in water!
        usage: /poseidon
    repair:
        description: Repairs the item you're holding!
        usage: /repair
    slay:
        description: Kills the specified player!
        usage: /slay
    smite:
        description: See slay.
        usage: /smite
    superjump:
        description: Leap tall structures in a single bound!
        usage: /superjump
    vulcan:
        description: Shoot fireballs with a swing of your hand!
        usage: /vulcan
    zeus:
        description: Strike lightning wherever you look!
        usage: /zeus
permissions:
    godpowers.*:
        description: Gives access to all godpowers commands.
        children:
            godpowers.bless: true
            godpowers.demigod: true
            godpowers.die: true
            godpowers.dupe: true
            godpowers.fusrodah: true
            godpowers.gaia: true
            godpowers.godmode: true
            godpowers.godmodeonlogin: true
            godpowers.godtools: true
            godpowers.hades: true
            godpowers.heal: true
            godpowers.hermes: true
            godpowers.inferno: true
            godpowers.jesus: true
            godpowers.maim: true
            godpowers.medusa: true
            godpowers.medusa.usehead: true
            godpowers.midas: true
            godpowers.plutus: true
            godpowers.poseidon: true
            godpowers.repair: true
            godpowers.slay: true
            godpowers.superjump: true
            godpowers.vulcan: true
            godpowers.zeus: true
    godpowers.bless:
        description: Gives permission to relevant command.
        default: op
    godpowers.demigod:
        description: Gives permission to relevant command.
        default: op
    godpowers.die:
        description: Gives permission to relevant command.
        default: op
    godpowers.dupe:
        description: Gives permission to relevant command.
        default: op
    godpowers.fusrodah:
        description: Gives permission to relevant command.
        default: op
    godpowers.gaia:
        description: Gives permission to relevant command.
        default: op
    godpowers.godmode:
        description: Gives permission to relevant command.
        default: op
    godpowers.godmodeonlogin:
        description: Allows godmode upon login.
        default: op
    godpowers.godtools:
        description: Gives permission to godtools.
        default: op
    godpowers.hades:
        description: Gives permission to relevant command.
        default: op
    godpowers.heal:
        description: Gives permission to relevant command.
        default: op
    godpowers.hermes:
        description: Gives permission to relevant command.
        default: op
    godpowers.inferno:
        description: Gives permission to relevant command.
        default: op
    godpowers.jesus:
        description: Gives permission to relevant command.
        default: op
    godpowers.maim:
        description: Gives permission to relevant command.
        default: op
    godpowers.medusa:
        description: Gives permission to relevant command.
        default: op
    godpowers.medusa.exempt:
        description: Exempts a player from medusa freeze.
        default: false
    godpowers.medusa.usehead:
        description: Allows a player to use a dropped medusa head.
        default: op
    godpowers.midas:
        description: Gives permission to relevant command.
        default: op
    godpowers.plutus:
        description: Gives permission to relevant command.
        default: op
    godpowers.poseidon:
        description: Gives permission to relevant command.
        default: op
    godpowers.repair:
        description: Gives permission to relevant command
        default: op
    godpowers.slay:
        description: Gives permission to relevant command.
        default: op
    godpowers.superjump:
        description: Gives permission to relevant command.
        default: op
    godpowers.vulcan:
        description: Gives permission to relevant command.
        default: op
    godpowers.zeus:
        description: Gives permission to relevant command.
        default: op
